/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import util.koneksi;
import java.sql.SQLException;

/**
 *
 * @author Plaza
 */
public class ViewCariTeman extends javax.swing.JFrame {

    /**
     * Creates new form ViewCariTeman
     */
    public ViewCariTeman() {
        initComponents();
        tampildata();
    }
public void tampildata(){
    DefaultTableModel table = new DefaultTableModel();
    
    table.addColumn("id");
    table.addColumn("nama");
    table.addColumn("nope");
    table.addColumn("email");
    
    tb_carinama.setModel(table);
    
    try {
        koneksi koneksi = new koneksi();
        koneksi.koneksidatabase();
        String querytampil = "select * from tbl_teman ";
        
        ResultSet res = koneksi.state.executeQuery(querytampil);
        
        while(res.next()){
            table.addRow(new Object[]{
            res.getString("id"),res.getString("nama"),res.getString("nope"),res.getString("email")
            });
            tb_carinama.setModel(table);
        }
    } catch (SQLException e) {
        System.err.println(""+e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_carinama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_carinama = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cari Nama :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        tf_carinama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_carinamaKeyReleased(evt);
            }
        });
        getContentPane().add(tf_carinama, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 11, 280, -1));

        tb_carinama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_carinama);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_carinamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_carinamaKeyReleased
        // TODO add your handling code here:
         DefaultTableModel table = new DefaultTableModel();
         String nama = tf_carinama.getText();
    
    table.addColumn("id");
    table.addColumn("nama");
    table.addColumn("nope");
    table.addColumn("email");
    
    tb_carinama.setModel(table);
    
    try {
        koneksi koneksi = new koneksi();
        koneksi.koneksidatabase();
        String querytampil = "select * from tbl_teman where nama like '%"+nama+"%'";
        
        ResultSet res = koneksi.state.executeQuery(querytampil);
        
        while(res.next()){
            table.addRow(new Object[]{
            res.getString("id"),res.getString("nama"),res.getString("nope"),res.getString("email")
            });
            tb_carinama.setModel(table);
        }
    } catch (SQLException e) {
        System.err.println(""+e);
    }
    }//GEN-LAST:event_tf_carinamaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCariTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCariTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCariTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCariTeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCariTeman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_carinama;
    private javax.swing.JTextField tf_carinama;
    // End of variables declaration//GEN-END:variables
}
